services:
  postgres:
    image: postgres:16-alpine
    container_name: shopmind-postgres
    environment:
      POSTGRES_DB: shopmind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shopmind"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: src/Shop.Api/Dockerfile
    container_name: shopmind-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "Host=postgres;Port=5432;Database=shopmind;Username=postgres;Password=postgres"
      Jwt__Secret: "shopmind-dev-secret-key-change-me-please-32chars!"
      Jwt__Issuer: "ShopMind"
      Jwt__Audience: "ShopMind"
      Redis__ConnectionString: "redis:6379"
      Redis__Enabled: "true"
      Redis__DefaultTtlSeconds: "90"
    ports:
      - "5000:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:7-alpine
    container_name: shopmind-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
  redisdata:
